language: perl
sudo: false
perl:
  - "5.24"
  - "5.26"
  - "5.28"
  - dev
matrix:
  include:
    - perl: "5.28"
      env: COVERAGE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
